#registration
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://13.209.22.155:3306/cuptea?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 9854

    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-name: kakao
                        client-id: e262931ced52942fd805e1c470e96856
                        client-secret: UCNkurwHuW9Kiw9GKE68vDcwYpFXxm00
                        redirect-uri: http://localhost:9090/service-api/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_post
                        scope: profile_nickname, profile_image
                    google:
                        client-name: google
                        client-id: 791423024934-8femgfvimgqkrhskg8dge81a66i697r2.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://localhost:9090/service-api/login/oauth2/code/google
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_post
                        scope: profile, email
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
          hibernate:
                    format_sql: true

    jwt:
        secret: dkssudgktpdyzjqxldpdhtlsrjtdmfghksdudgkqslekzjqxlqlalfq960212#!$%
        access-expiration: 1800000L
        refresh-expiration: 86400000L
    mail:
        host: smtp.gmail.com # SMTP 호스트
        port: 587
        username: sgwonbe212@gmail.com
        password: vgdynjclkbiuaflr
        properties:
            mail:
                smtp:
                    auth: true # 사용자 인증 시도
                    timeout: 5000 # 타임아웃 시간
                    starttls:
                        enable: true










