cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${EC2_HOST}:3306/cuptea?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}e262931ced52942fd805e1c470e96856
            client-secret: ${KAKAO_CLIENT_SECRET}UCNkurwHuW9Kiw9GKE68vDcwYpFXxm00
            redirect-uri: http://${EC2_HOST}:9090/service-api/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, profile_image
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}791423024934-8femgfvimgqkrhskg8dge81a66i697r2.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}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
            redirect-uri: http://${EC2_HOST}:9090/service-api/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile, email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      enabled: true

  jwt:
    secret: ${JWT_SECRET}
    access-expiration: 1800000L
    refresh-expiration: 86400000L
  mail:
    host: smtp.gmail.com # SMTP 호스트
    port: 587
    username: ${GOOGLE_MAIL_USERNAME}
    password: ${GOOGLE_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도
          timeout: 5000 # 타임아웃 시간
          starttls:
            enable: true











