
name: cuptea-service deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle Wrapper
      run: ./gradlew build --exclude-task test

        #Gradle Build 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    
